/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.CustomerController;
import Controller.ItemController;
import Controller.OrderController;
import dto.CustomerDto;
import dto.Itemdto;
import dto.OrderDetailDto;
import dto.Orderdto;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kaweesha
 */
public class OrderView extends javax.swing.JPanel {
    private ItemController itemController=new ItemController();
    private CustomerController customerController=new CustomerController();
   private ArrayList<OrderDetailDto> orderDetailDtos=new ArrayList<>();



    /**
     * Creates new form OrderView
     */
    public OrderView() {
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCustId = new javax.swing.JLabel();
        lblItemData = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        customerSearchbtn = new javax.swing.JButton();
        Itemsearchbtn = new javax.swing.JButton();
        cartbtn = new javax.swing.JButton();
        orderbtn = new javax.swing.JButton();
        txtsearchid = new javax.swing.JTextField();
        txtsearchcode = new javax.swing.JTextField();
        txtOrder = new javax.swing.JTextField();
        txtCustId = new javax.swing.JTextField();
        txtItemId = new javax.swing.JTextField();
        txtQty = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        txtDiscount = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 25)); // NOI18N
        jLabel1.setText("Order Form ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("order Id");

        lblCustId.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblCustId.setText("Customer Id");

        lblItemData.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblItemData.setText("Item Code");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("Qty");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("Discount");

        customerSearchbtn.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        customerSearchbtn.setText("Search");
        customerSearchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerSearchbtnActionPerformed(evt);
            }
        });

        Itemsearchbtn.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        Itemsearchbtn.setText("Search");
        Itemsearchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemsearchbtnActionPerformed(evt);
            }
        });

        cartbtn.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        cartbtn.setText("Add to Cart ");
        cartbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartbtnActionPerformed(evt);
            }
        });

        orderbtn.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        orderbtn.setText("Place Order");
        orderbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderbtnActionPerformed(evt);
            }
        });

        txtsearchid.setText("jTextField1");

        txtsearchcode.setText("jTextField2");

        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCart);

        txtDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiscountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCustId)
                                .addGap(34, 34, 34)
                                .addComponent(txtCustId, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(customerSearchbtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtsearchid, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblItemData)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtItemId, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Itemsearchbtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtsearchcode, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(28, 28, 28)
                                .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cartbtn)
                                    .addComponent(orderbtn))))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCustId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCustId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblItemData)
                            .addComponent(txtItemId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerSearchbtn)
                            .addComponent(txtsearchid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Itemsearchbtn)
                            .addComponent(txtsearchcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cartbtn)
                        .addGap(18, 18, 18)
                        .addComponent(orderbtn)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void customerSearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerSearchbtnActionPerformed
      searchCustomer();
    }//GEN-LAST:event_customerSearchbtnActionPerformed

    private void ItemsearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemsearchbtnActionPerformed
       searchItem();
    }//GEN-LAST:event_ItemsearchbtnActionPerformed

    private void cartbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartbtnActionPerformed
      addToCart();
    }//GEN-LAST:event_cartbtnActionPerformed

    private void orderbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderbtnActionPerformed
       placeOrder();
    }//GEN-LAST:event_orderbtnActionPerformed

    private void txtDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiscountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Itemsearchbtn;
    private javax.swing.JButton cartbtn;
    private javax.swing.JButton customerSearchbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCustId;
    private javax.swing.JLabel lblItemData;
    private javax.swing.JButton orderbtn;
    private javax.swing.JTable tblCart;
    private javax.swing.JTextField txtCustId;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtItemId;
    private javax.swing.JTextField txtOrder;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtsearchcode;
    private javax.swing.JTextField txtsearchid;
    // End of variables declaration//GEN-END:variables
 public void searchCustomer(){
     String customerId=txtCustId.getText();
     try{
         CustomerDto customerDto=customerController.searchCustomer(customerId);
         if(customerDto!=null){
             txtsearchid.setText(customerDto.getCustTitle()+"."+customerDto.getCustName());

         }else{
             JOptionPane.showMessageDialog(this,"Customer Not Found");

         }

     } catch (Exception e) {
         e.printStackTrace();
         JOptionPane.showMessageDialog(this,e.getMessage());

     }
 }
public  void searchItem(){
     String itemCode= txtItemId.getText();
     try{
         Itemdto itemdto=itemController.searchItem(itemCode);
         if(itemdto!=null){
             txtsearchcode.setText(itemdto.getDescription()+"|"+itemdto.getPacksize()+"|"+itemdto.getQtyOnHand()+"|"+itemdto.getUnitprice());

         }else {
             JOptionPane.showMessageDialog(this,"Item Not Found");
         }

     } catch (Exception e) {
         e.printStackTrace();
         JOptionPane.showMessageDialog(this,e.getMessage());

     }
}
  private void loadTable(){
     String columns[]={"Item code","qty","Discount"};
     DefaultTableModel dtm=new DefaultTableModel(columns,0){
         public boolean isCellEditable(){
             return false;
         }

     };
     tblCart.setModel(dtm);
  }
 public void addToCart(){
     try{
         OrderDetailDto dto=new OrderDetailDto();
         dto.setItemCode(txtItemId.getText());
         dto.setQty(Integer.parseInt(txtQty.getText()));
         dto.setDiscount(Double.parseDouble(txtDiscount.getText()));

         orderDetailDtos.add(dto);
         Object [] rowdata={dto.getItemCode(),dto.getQty(),dto.getDiscount()};
         DefaultTableModel dtm=(DefaultTableModel) tblCart.getModel();
         dtm.addRow(rowdata);

     } catch (Exception e) {
         e.printStackTrace();
         JOptionPane.showMessageDialog(this,e.getMessage());

     }
 }
 private void clearItems(){
     txtCustId.setText("");
     txtItemId.setText("");
     txtDiscount.setText("");
     txtQty.setText("");
 }
    public void placeOrder() {
        try {
            Orderdto orderdto=new Orderdto();
            orderdto.setOid(txtOrder.getText());
            orderdto.setCustid(txtCustId.getText());
            SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
            String date=sdf.format(new Date());
            orderdto.setDate(date);
            orderdto.setOrderDetailDtos(orderDetailDtos);
            OrderController controller=new OrderController();
            System.out.println(orderdto.toString());
            String resp=controller.placeOrder(orderdto);
            JOptionPane.showMessageDialog(this,resp);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,"Error Placing Order"+e.getMessage());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Error placing order"+e.getMessage());
        }
    }

}
